### ISSUE TITLE
Parentheticals can't be italicized

### ISSUE THREAD

**Issue by cantrell** [jonnygreenwald/fountain-js#17]
If a parenthetical is italicized, it won't match the parenthetical regular expression. I've seen scripts where writers will italicize the odd parenthetical. If you want to add support, here's an updated regular expression for `token.ts`.

`const parts: string[] = match[3].split(/(\*?\(.+\)\*?)(?:\n+)/).reverse();`

Thanks!

**Comment by jonnygreenwald** [comment]
I'm working on cleaning up some regex, so will look into this as well. 

Currently, emphasis _inside_ the parenthetical works like so:

```fountain
STEEL
(*starting the engine*)
So much for retirement!
```

The parenthesis will not be emphasized, but the important stuff inside will be. 

As a note, Highland 2 doesn't actually allow the emphasis to wrap the parenthetical. It will simply turn it into dialogue. That being said, there's nothing in spec that indicates you cannot do this so I'll fiddle around with it as I'm doing some cleaning up.

**Comment by cantrell** [comment]
I would certainly do it the way you describe (emphasis inside the parentheses). But I somehow ended up with the Fountain version of a Breaking Bad script what was written as shown below. I'm sure this went through a bunch of conversions, so it's likely not how it was originally written, but as you mention, it doesn't violate any specs, so it seems like it should work. (And yes, Highland 2 treats this as dialogue.)

<img width="244" alt="image" src="https://github.com/jonnygreenwald/fountain-js/assets/138986/8da8d419-e0e8-4475-ab51-d0dac7929270">

Thanks!

**Comment by jonnygreenwald** [comment]
Cool! Thanks for the context. 

To be fair, the writer (Vince?) probably wrote it Final Draft, which I doubt cares so it makes sense to me that Fountain shouldn't either in my opinion.

**Comment by jonnygreenwald** [comment]
My latest commit cfb1e2951ccd9a5fe890b5e03943093994b07140 should fix the issue. 

I'm working on one last thing regarding emphasis to improve flanking, etc., so I haven't merged this into the main branch yet. I'm hoping to be done with it in the next few days. Apologies for the longer-than-usual delay on this one.

**Comment by jonnygreenwald** [comment]
Version `1.1.3` is up, which should hopefully close this out. 

Sorry it took longer than expected, I started to spin my wheels on the inline improvements, so I've decided to break that out into its own round of changes as to not drag this out forever.

**Comment by cantrell** [comment]
As always, much appreciated!
